# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - webquick2602cryc

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          registry: antuxcontainerregistry1.azurecr.io/
          username: ${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_23CA93880CA4447A8C7C6BCEEDE48D20 }}
          password: ${{ secrets.AZUREAPPSERVICE_CONTAINERPASSWORD_BE60A2CC2C3A46E4B59CA12087D2C323 }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: antuxcontainerregistry1.azurecr.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_23CA93880CA4447A8C7C6BCEEDE48D20 }}/hello:world-latest:${{ github.sha }}
          file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    needs: build
    
    steps:
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_90632E202AD94E5D867BCEB84E1467E2 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_1BA3E03F223F4594B774E66F0A85D8A8 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_3E7472DFE228423CA2D7CC814CFB3AD9 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'webquick2602cryc'
          slot-name: 'Production'
          images: 'antuxcontainerregistry1.azurecr.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_23CA93880CA4447A8C7C6BCEEDE48D20 }}/hello:world-latest:${{ github.sha }}'
          